name: deploy

on:
  push:
    branches: [main]

jobs:
  launch-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.4
        with:
          cache: npm
          cache-dependency-path: package-lock.json
          node-version: 16
      - name: check env
        run: echo ${{secrets.PASSWORD}}

      - name: Node VPS Deployment
        uses: Techie-Pi/node-vps-deployment@v1.1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          key: ${{ secrets.KEY }}
          script: |
            cd discordbot
            git pull
            npm i
            pm2 update
