name: deploy

on:
  push:
    branches: [main]

jobs:
  launch-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.4
        with:
          cache: npm
          cache-dependency-path: package-lock.json
          node-version: 16

      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: SSH Remote Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.KEY }}
          username: ${{ secrets.USERNAME }}
          envs:
            host: ${{ secrets.HOST }}
            key: ${{ secrets.KEY }}
            username: ${{ secrets.USERNAME }}
            script: |
              cd discordbot
              git pull
              npm i

