name: Push-to-EC2

# Trigger deployment only on push to master branch
on: [push, workflow_dispatch]
  # push:
  #   branches:
  #     - main

  # workflow_dispatch:
  #   inputs:
  #     logLevel:
  #       description: 'Log level'     
  #       required: true
  #       default: 'warning' 
  #       type: choice
  #       options:
  #       - info
  #       - warning
  #       - debug 
  #     tags:
  #       description: 'Test scenario tags'
  #       required: false 
  #       type: boolean
  #     environment:
  #       description: 'Environment to run tests against'
  #       type: environment
  #       required: true 
  

jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest

    steps:
      - name: Run script
        run: echo Hello world!

  # log-the-inputs:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: |
  #         echo "Log level: $LEVEL"
  #         echo "Tags: $TAGS"
  #         echo "Environment: $ENVIRONMENT"
  #       env:
  #         LEVEL: ${{ inputs.logLevel }}
  #         TAGS: ${{ inputs.tags }}
  #         ENVIRONMENT: ${{ inputs.environment }}

    

    # steps:
    #   - name: Checkout the files
    #     uses: actions/checkout@v2

    #   - name: Deploy to Server 1
    #     uses: easingthemes/ssh-deploy@main
    #     env:
    #       SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
    #       REMOTE_HOST: ${{ secrets.HOST_DNS }}
    #       REMOTE_USER: ${{ secrets.USERNAME }}
    #       TARGET: ${{ secrets.TARGET_DIR }}
