name: Push-to-EC2

# Trigger deployment only on push to master branch
on: 
  push:
  workflow_run:
    workflows: [Build]
    types: [completed]
    branches: [main]

jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest
    
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed'

    steps:
    - name: Run script
      run: echo Hello world!

    # steps:
    #   - name: Checkout the files
    #     uses: actions/checkout@v2

    #   - name: Deploy to Server 1
    #     uses: easingthemes/ssh-deploy@main
    #     env:
    #       SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
    #       REMOTE_HOST: ${{ secrets.HOST_DNS }}
    #       REMOTE_USER: ${{ secrets.USERNAME }}
    #       TARGET: ${{ secrets.TARGET_DIR }}
